spring.application.name=CarbonTrace
spring.datasource.url=${SPRING_DATASOURCE_URL:SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:SEU_USUARIO}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:SUA_SENHA}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect
server.port=8080